version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.0
  node: circleci/node@5.0.2
jobs:
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Build
          command: |
            yarn global add expo-cli
            yarn
            cd MobileExample
            yarn
            yarn web:build
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: 43:a5:19:51:55:12:95:cc:70:30:4e:12:12:e6:13:32
          build-dir: MobileExample/web-build

workflows:
  Build and Deploy:
    jobs:
      - build_deploy
